version: "3"
services:
  builder:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: icmdb/iwebhooks

  iwebhooks:
    hostname: iwebhooks
    container_name: iwebhooks
    image: icmdb/iwebhooks
    environment:
      - APP_ADDR=0.0.0.0
      - APP_PORT=8080
      - APP_DEBUG=True
    ports:
      - 8080:8080
    restart: always
